### ISSUE TITLE
Model data not available due to git LFS

### ISSUE THREAD

**Issue by BradBalderson** [AIRI-Institute/DeepCT-inference-helper#1]
Referencing this thread on the other github repo as an issue with this one as well: https://github.com/AIRI-Institute/DeepCT/issues/75

@msindeeva also posted on the other thread, asking if the weights between this repo and the standard DeepCT repo are the same?

Thanks alot!!

**Comment by msindeeva** [comment]
Thanks again for noticing the same issue with git-lfs in this repository, I’ve moved files previously stored via git-lfs to our NextCloud server and updated instructions in the README.
No, the weights are different between these two repositories. IIRC the weights in the [DeepCT](https://github.com/AIRI-Institute/DeepCT) repo are from the latest round of training. The weights in this repository are a bit older and are meant to be used together with logistic regression weights to predict gain/loss of enhancer upon mutation.
Sorry for the late reply again 🙃 , I’ll try my best to respond quicker in the future
